platform :ios, '6.0'

pod 'JSMessagesViewController', :git => 'git@github.com:jessesquires/MessagesTableViewController.git'
pod 'ObjectiveDDP', :git => 'git@github.com:boundsj/ObjectiveDDP.git', :branch => 'master'
pod 'SocketRocket', :git => 'git@github.com:square/SocketRocket.git'
